### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by btimofeev** [SubhamTyagi/Last-Launcher#110]
The application crashes periodically. Today crashed when I had logcat connected, the error is:

`2020-12-30 23:10:18.337 24966-24966/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.subhamtyagi.lastlauncher, PID: 24966
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at io.github.subhamtyagi.lastlauncher.LauncherActivity$b.onPostExecute(:3)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)`

App. version: 0.15 from f-droid
Android: 10
Phone: Xiaomi Mi A3

**Comment by btimofeev** [comment]
I have this crash very often when I install applications. I found that in the code you remove the application from the list in a foreach loop https://github.com/SubhamTyagi/Last-Launcher/blob/3368bf9486a52f473691d0ecffaf50b742e062bc/app/src/main/java/io/github/subhamtyagi/lastlauncher/LauncherActivity.java#L655-L657 

But as this article suggests https://www.baeldung.com/java-concurrentmodificationexception, this leads to java.util.ConcurrentModificationException. Most likely the problem is somewhere here or in a similar place.

**Comment by btimofeev** [comment]
I have not seen this crash again after fixing
