### ISSUE TITLE
[meta] Fonts selection improvement

### ISSUE THREAD

**Issue by SubhamTyagi** [SubhamTyagi/Last-Launcher#25]
What must be do before stable version

- Copy user selected fonts to apps private storage.
- Reset fonts to default settings entry.
- Fonts selection improvement (search for fonts on internal storage).
-

**Comment by SubhamTyagi** [comment]
Worst case of 


java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.subhamtyagi.lastlauncher/io.github.subhamtyagi.lastlauncher.LauncherActivity}: java.lang.RuntimeException: Font not found /storage/emulated/0/Download/product-sans/Product Sans Italic.ttf
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
	at ....more
Caused by: java.lang.RuntimeException: Font not found /storage/emulated/0/Download/product-sans/Product Sans Italic.ttf
	at android.graphics.Typeface.createFromFile(Typeface.java:252)
	at io.github.subhamtyagi.lastlauncher.LauncherActivity.onCreate(:5)
	at android.app.Activity.performCreate(Activity.java:6857)
	at 
	...more
