### ISSUE TITLE
Backup button makes a crash on android 6

### ISSUE THREAD

**Issue by SubhamTyagi** [SubhamTyagi/Last-Launcher#55]
dear devs，the backup button makes a crash on android 6, can you fix it all just give me some advice on that.

_Originally posted by @wyfhust in https://github.com/SubhamTyagi/Last-Launcher/issues/28#issuecomment-615252303_

**Comment by psychoreactorq** [comment]
I can confirm this using android 6.0.1 on a ZTE ZFive 2 Z836BL. This app crashes repeatedly and without fail on Android 6.

**Comment by psychoreactorq** [comment]
I tested this out with Android Studio, and here is the output and the solution.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.subhamtyagi.lastlauncher.debug, PID: 19830
    java.lang.IllegalArgumentException: Unknown pattern character 'Y'
        at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
        at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:305)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:258)
        at io.github.subhamtyagi.lastlauncher.utils.SpUtils.saveSharedPreferencesToFile(SpUtils.java:201)
        at io.github.subhamtyagi.lastlauncher.utils.DbUtils.saveDbTOFile(DbUtils.java:80)
        at io.github.subhamtyagi.lastlauncher.dialogs.GlobalSettingsDialog.backup(GlobalSettingsDialog.java:313)
        at io.github.subhamtyagi.lastlauncher.dialogs.GlobalSettingsDialog.onClick(GlobalSettingsDialog.java:142)
        at android.view.View.performClick(View.java:5205)
        at android.view.View$PerformClick.run(View.java:21164)
        at android.os.Handler.handleCallback(Handler.java:745)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:5440)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    FATAL EXCEPTION: main
    Process: io.github.subhamtyagi.lastlauncher.debug, PID: 19830
    java.lang.IllegalArgumentException: Unknown pattern character 'Y'
        at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
        at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:305)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:258)
        at io.github.subhamtyagi.lastlauncher.utils.SpUtils.saveSharedPreferencesToFile(SpUtils.java:201)
        at io.github.subhamtyagi.lastlauncher.utils.DbUtils.saveDbTOFile(DbUtils.java:80)
        at io.github.subhamtyagi.lastlauncher.dialogs.GlobalSettingsDialog.backup(GlobalSettingsDialog.java:313)
        at io.github.subhamtyagi.lastlauncher.dialogs.GlobalSettingsDialog.onClick(GlobalSettingsDialog.java:142)
        at android.view.View.performClick(View.java:5205)
        at android.view.View$PerformClick.run(View.java:21164)
        at android.os.Handler.handleCallback(Handler.java:745)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:5440)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

all you need to do is replace YYYY with yyyy in SpUtils.java line 201, I believe this is compatible with the newer android versions that support having it capitalized.

https://stackoverflow.com/questions/25337241/java-lang-illegalargumentexception-illegal-pattern-character-y-for-simpledate

**Comment by SubhamTyagi** [comment]
Bug fix for this has been landed but confirmation is need to close this issue
