### ISSUE TITLE
[meta]Crashes reports

### ISSUE THREAD

**Issue by SubhamTyagi** [SubhamTyagi/Last-Launcher#74]
1st reports

This archive file contains crashes since 6 may( version 13)
[crashReports_f_6_to_26_5.zip](https://github.com/SubhamTyagi/Last-Launcher/files/4680295/crashReports_f_6_to_26_5.zip)

**Comment by SubhamTyagi** [comment]
[crashes.zip](https://github.com/SubhamTyagi/Last-Launcher/files/5664134/crashes.zip)

**Comment by SubhamTyagi** [comment]
1: java.lang.RuntimeException: An error occurred while executing doInBackground()
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.github.subhamtyagi.lastlauncher.model.Apps.getAppName()' on a null object reference
	at io.github.subhamtyagi.lastlauncher.LauncherActivity$SortTask.lambda$doInBackground$0(LauncherActivity.java:1223)
	at io.github.subhamtyagi.lastlauncher.-$$Lambda$LauncherActivity$SortTask$_p3DhLpQhRSHfo273ciH3-4PW2A.compare(lambda)`

2: `java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4419)
	at android.view.ViewGroup.addView(ViewGroup.java:4260)
	at android.view.ViewGroup.addView(ViewGroup.java:4232)
	at io.github.subhamtyagi.lastlauncher.LauncherActivity$SortTask.onPostExecute(LauncherActivity.java:1211)
	at io.github.subhamtyagi.lastlauncher.LauncherActivity$SortTask.onPostExecute(LauncherActivity.java:1201)
	at android.os.AsyncTask.finish(AsyncTask.java:667)`

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/Last-Launcher/issues/74#issuecomment-782577432

1. -> fixed
2. -> fixed
